service: epsagon-acceptance

provider:
  name: aws
  runtime: ${opt:runtime}
  region: ${opt:region, 'us-east-1'}
  stage: ${self:custom.buildNumber}-${opt:runtimeName}
  environment:
    STAGE: dev
    EPSAGON_DEBUG: "TRUE"
  package:
    exclude:
    - './**'
    - 'node_modules/**'

custom:
  buildNumber: ${opt:buildNumber}
  pythonRequirements:
    dockerizePip: non-linux
    dockerSsh: true

functions:
  sanity:
    handler: handler.sanity
    events:
      - http:
          path: sanity
          method: post

  labels:
    handler: handler.labels

  http-test:
    handler: handler.read_data
    events:
      - http:
          path: http_test
          method: get

plugins:
  - serverless-python-requirements
