language: python
notifications:
  slack: epsagon:Q0XcrHSJRI5YkYftfUzl83Lx
python:
- '3.6'
install:
- pip install -r requirements-dev.txt
- pip install pylint
before_script:
- 'pylint --msg-template=''{path}:{line}: [{msg_id}({symbol}) {obj}] {msg}'' epsagon/'
script:
- tox
deploy:
  provider: pypi
  user: epsagon
  distribution: bdist_wheel sdist
  skip_existing: true
  password: ${PYPI_PASSWORD}
  on:
    branch: testing_travis_pypi_deployment
  server: https://test.pypi.org/legacy/
